import type { CreateTemplate } from "@/types/template";

export const CREATE_TEMPLATES: CreateTemplate[] = [
  {
    id: "page-generic",
    label: "Generic",
    description: "Create a custom page",
    createType: "page",
    templateType: "generic",
    initialTitle: "",
    initialContent: "",
  },
  {
    id: "page-diary",
    label: "Daily Diary",
    description: "Reflect on your day",
    createType: "page",
    templateType: "diary",
    initialTitle: "Diary - ",
    initialContent: "<p>Today I felt...</p>",
  },
  {
    id: "page-fact",
    label: "Fact Note",
    description: "Store objective information",
    createType: "page",
    templateType: "fact",
    initialTitle: "Fact - ",
    initialContent: "<p>Fact:</p>",
  },
  {
    id: "page-event",
    label: "Event",
    description: "Record something that happened",
    createType: "page",
    templateType: "event",
    initialTitle: "Event - ",
  },
  {
    id: "page-system",
    label: "System",
    description: "System-style page (uses generic type)",
    createType: "page",
    templateType: "generic",
    initialTitle: "System - ",
  },
  {
    id: "book-generic",
    label: "Generic",
    description: "Book that can include any type of page",
    createType: "book",
    templateType: "generic",
    initialTitle: "Book - Generic",
  },
  {
    id: "book-diary",
    label: "Diary",
    description: "Book for diary pages",
    createType: "book",
    templateType: "diary",
    initialTitle: "Book - Diary",
  },
  {
    id: "book-fact",
    label: "Fact",
    description: "Book for fact pages",
    createType: "book",
    templateType: "fact",
    initialTitle: "Book - Fact",
  },
  {
    id: "book-event",
    label: "Event",
    description: "Book for event pages",
    createType: "book",
    templateType: "event",
    initialTitle: "Book - Event",
  },
  {
    id: "book-system",
    label: "System",
    description: "System-style book (uses generic behavior)",
    createType: "book",
    templateType: "generic",
    initialTitle: "Book - System",
  },
];
